### ISSUE TITLE
Allow all claim names to be overridden via configuration

### ISSUE THREAD

**Issue by vlaurin** [quickcase/spring-oidc#37]
To support a broader range of OIDC providers, including bespoke providers with greater divergence from the OIDC standard, all claims used by QuickCase should be overridable via configuration.

For example:
```yml
quickcase:
  oidc:
    claims:
      user:
        override: # Individually remap claims
          qc_organisations: app_organisations
          
```
