### ISSUE TITLE
Allow private claims to be prefixed via configuration

### ISSUE THREAD

**Issue by vlaurin** [quickcase/spring-oidc#39]
Some OIDC providers, such as AWS Cognito, forcibly prefix all private claims, for example with `custom:`.

While this is catered for by #37 , explicitly overriding all claim names to add a similar prefix is redundant and an easier approach would be to allow for a custom prefix to be optionally defined via configuration.

For example:

```yml
quickcase:
  oidc:
    claims:
      user:
        prefix: 'custom:'
          
```
