### ISSUE TITLE
Add support for composite name claims

### ISSUE THREAD

**Issue by vlaurin** [quickcase/spring-oidc#56]
By default, QuickCase expect the full name to be extracted from a single, overridable `name` claim. However, this doesn't offer support for configurations where the `name` claim is not used and instead claims `given_name` and `family_name` are used in conjunction.

Support should be added to allow `name` to be configured as the concatenation of multiple claims, for example using a template string.

```yml
quickcase:
  oidc:
    claims:
      names: '${given_name} ${family_name}'
```
